### ISSUE TITLE
In the "More Complex Example", why are any slashes in the regexes removed?

### ISSUE THREAD

**Issue by xavi** [alexanderkiel/phrase#1]
In https://github.com/alexanderkiel/phrase#more-complex-example , why this code...

```
(case (str/replace (str re) #"/" "")
  "\\d" "number"
  ; ...
  )
```                
is not simply...?

```
(case (str re)
  "\\d" "number"
  ; ...
  )
```

**Comment by alexanderkiel** [comment]
Because in ClojureScript, `(str #"\d")` evaluates to `"/\\d/"` while in Clojure it evaluates to `"\\d"`. I have no idea why this is the case.

**Comment by xavi** [comment]
I see. Thanks!

Maybe ClojureScript behavior comes from JavaScript behavior, where

```
(new RegExp('\\d')).toString()
// => "/\d/"
```
