### ISSUE TITLE
Update ClojureScript to Support Java 9

### ISSUE THREAD

**Issue by alexanderkiel** [alexanderkiel/phrase#10]
The current version of ClojureScript (1.9.946) depends on `javax.xml.bind.DatatypeConverter` which is no longer available by default in Java 9. [CLJS-2377](https://dev.clojure.org/jira/browse/CLJS-2377) solves this problem but is not released yet.

**Comment by tirkarthi** [comment]
[Clojurescript 1.10](https://clojurescript.org/news/2018-03-26-release) was released . I have tested it with the latest CLJS release and JDK 9. Tests pass.
