### ISSUE TITLE
Add required keys phraser example to README?

### ISSUE THREAD

**Issue by leblowl** [alexanderkiel/phrase#18]
I think it might be helpful to add the example phraser in issue #8 to the README. The example shows how to generate a phrase for a required spec key that is missing. I feel this is a very common use-case. Any thoughts? Thanks

**Comment by alexanderkiel** [comment]
I think it would be good to have an extra document with specific examples. I would be happy if you just open a pull request with a `doc/examples.md` and add the example you have in mind.

**Comment by leblowl** [comment]
Ok, sounds good
