### ISSUE TITLE
Binding pred

### ISSUE THREAD

**Issue by jeans11** [alexanderkiel/phrase#24]
Hello guys!

There is a reason about this:

```clojure
(def enum #{"foo" "bar"})

(defphraser enum [_ _ _] (str "Error")) ;; not work when there is an error

(defphraser #{"foo" "bar"} [_ _ _] (str "Error")) ;; work when there is an error
```

Thanks!

**Comment by alexanderkiel** [comment]
If you use the predicate `#{"foo" "bar"}` in your specs, you also have to use `#{"foo" "bar"}` in `defphraser`. I don't resolve pred's, because I can't know what you use in your specs.

**Comment by jeans11** [comment]
Thanks for the anwser!
